# Generated by Django 6.0.5 on 2026-05-15 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=10)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id_moto', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('cilindraje', models.CharField(max_length=30)),
                ('kilometraje', models.CharField(blank=True, max_length=30, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
    ]
