# Generated by Django 6.0.5 on 2026-05-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Por definir', max_length=100),
        ),
    ]
