# Generated by Django 6.0.5 on 2026-06-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
