# Generated by Django 6.0.5 on 2026-06-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
