# Generated by Django 6.0.5 on 2026-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_moto_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.AlterField(
            model_name='log',
            name='accion_realizada',
            field=models.CharField(db_column='accion_realizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='descripcion',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora'),
        ),
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
