# Generated by Django 6.0.5 on 2026-06-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_empleado_rol_remove_empleado_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('recibo', 'Recibo de venta (sin DIAN)'), ('factura', 'Factura electrónica (con DIAN)')], default='recibo', max_length=20, verbose_name='Tipo Documento')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT / Documento')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='IVA (%)')),
                ('moneda_simbolo', models.CharField(default='$', max_length=5, verbose_name='Símbolo Moneda')),
                ('moneda_nombre', models.CharField(default='COP', max_length=20, verbose_name='Nombre Moneda')),
                ('stock_minimo_alerta', models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo Alerta')),
                ('dias_credito_default', models.PositiveIntegerField(default=30, verbose_name='Días Crédito (Defecto)')),
                ('backup_automatico_activo', models.BooleanField(default=False, verbose_name='Backup Automático Activo')),
                ('ultima_copia_seguridad', models.DateTimeField(blank=True, null=True, verbose_name='Última Copia Realizada')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
