# Generated by Django 6.0.5 on 2026-06-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_configuracionsistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='ultima_copia_seguridad',
        ),
    ]
