# Generated by Django 6.0.5 on 2026-06-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
