# Generated by Django 6.0.4 on 2026-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_moto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='maneja_iva',
            field=models.BooleanField(default=False, verbose_name='¿Es responsable de IVA?'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='prefijo_factura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo (ej: SETP)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='resolucion_dian',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolución DIAN'),
        ),
    ]
