# Generated by Django 6.0.5 on 2026-07-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_configuracionsistema_maneja_iva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
