# Generated by Django 6.0.5 on 2026-07-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'permissions': [('can_create_backup', 'Puede crear copias de seguridad')]},
        ),
    ]
