# Generated by Django 6.0.5 on 2026-05-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='S/N', max_length=100),
            preserve_default=False,
        ),
    ]
