# Generated by Django 6.0.5 on 2026-06-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Fabricante')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_fabricante',
            field=models.ForeignKey(blank=True, db_column='id_fabricante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.fabricante', verbose_name='Fabricante'),
        ),
    ]
