# Generated by Django 6.0.5 on 2026-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_compra_id_usuario_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente de Pago')], default='Pendiente', max_length=20),
        ),
    ]
