# Generated by Django 6.0.5 on 2026-07-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_compra_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaproducto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
