# Generated by Django 6.0.5 on 2026-05-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_categoria_options_alter_marcaproducto_options_and_more'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaServicio',
            fields=[
                ('id_lista_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('precio_base_mano_obra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
            },
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Orden de Servicio', 'verbose_name_plural': 'Órdenes de Servicio'},
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.servicio')),
                ('id_lista_servicio', models.ForeignKey(db_column='id_lista_servicio', on_delete=django.db.models.deletion.CASCADE, to='operaciones.listaservicio')),
            ],
            options={
                'verbose_name': 'Detalle del Servicio',
                'verbose_name_plural': 'Detalles de los Servicios',
            },
        ),
    ]
