# Generated by Django 6.0.5 on 2026-05-28 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_nombre'),
        ('inventario', '0003_alter_categoria_options_alter_marcaproducto_options_and_more'),
        ('operaciones', '0002_listaservicio_alter_servicio_options_detalleservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.IntegerField(unique=True)),
                ('fecha_venta', models.DateTimeField()),
                ('tipo_pago', models.CharField(max_length=90)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tipo', models.CharField(max_length=90)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='operaciones.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.CreateModel(
            name='CreditoPagado',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.servicio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.venta')),
            ],
            options={
                'verbose_name': 'Abono de Crédito',
                'verbose_name_plural': 'Abonos de Créditos',
            },
        ),
    ]
