# Generated by Django 6.0.4 on 2026-06-03 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_empleado'),
        ('operaciones', '0003_venta_detalleventa_creditopagado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditopagado',
            options={'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='id_credito',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='id_servicio',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='creditopagado',
            name='saldo_anterior',
        ),
        migrations.AddField(
            model_name='creditopagado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='creditopagado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditopagado',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo - Con deuda'), ('PAGADO', 'Pagado - Paz y salvo')], default='ACTIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.servicio')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.venta')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
        migrations.AddField(
            model_name='creditopagado',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='operaciones.credito'),
        ),
    ]
