# Generated by Django 6.0.4 on 2026-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_servicio_id_usuario_alter_servicio_mecanico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('RECIBO', 'Recibo de Venta'), ('FACTURA', 'Factura Electrónica')], default='RECIBO', max_length=20, verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
