# Generated by Django 6.0.4 on 2026-07-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_remove_venta_total_venta_monto_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='id_lista_servicio',
            field=models.ForeignKey(blank=True, db_column='id_lista_servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.listaservicio'),
        ),
    ]
