# Generated by Django 6.0.5 on 2026-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_detalleservicio_id_lista_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
