# Generated by Django 6.0.5 on 2026-07-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_credito_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
